INSERT INTO "TRANSACTION" (ID, AMOUNT, TYPE, PARENT_ID) VALUES (10, 5000.0, 'CARS', null);

INSERT INTO "TRANSACTION" (ID, AMOUNT, TYPE, PARENT_ID) VALUES (11, 10000.0, 'SHOPPING', 10);

INSERT INTO "TRANSACTION" (ID, AMOUNT, TYPE, PARENT_ID) VALUES (12, 5000.0, 'SHOPPING', 11);
